services:
  webcomic_reader:
    image: webcomic-reader:0.1.0
    build: .
    ports:
      - "8000:8000"
    environment:
      - COMICS_DIR=/comics
      - APP_VERSION=0.1.0
    volumes:
      - ./comics:/comics:ro
      - ./config:/app/config
      - ./data:/app/data
